# Generated by Django 2.1.2 on 2019-10-23 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20191023_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date_time',
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
