# Generated by Django 2.1.2 on 2019-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_auto_20191023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='additional_Info',
            field=models.TextField(default='unkown', max_length=50),
        ),
    ]
